# Archivo de migración
# Permite insertar datos iniciales en la base de datos para la app 'store'.
# Generated by Django 5.0.6 on 2025-06-29 08:46

from django.db import migrations

def seed_data(apps, schema_editor):
    # Obtenemos los modelos de la app 'store'
    Pais = apps.get_model('store', 'Pais')
    Provincia = apps.get_model('store', 'Provincia')
    Ciudad = apps.get_model('store', 'Ciudad')
    Producto = apps.get_model('store', 'Producto')
    FraseMotivacional = apps.get_model('store', 'FraseMotivacional')

    # --- Creación de Frases Motivacionales ---
    # get_or_create busca un objeto con estos parámetros. Si no lo encuentra, lo crea.
    FraseMotivacional.objects.get_or_create(texto="El único modo de hacer un gran trabajo es amar lo que haces.")
    FraseMotivacional.objects.get_or_create(texto="Cree que puedes y ya estás a medio camino.")
    FraseMotivacional.objects.get_or_create(texto="El futuro pertenece a quienes creen en la belleza de sus sueños.")

    # --- Creación de Localizaciones ---
    ecuador, _ = Pais.objects.get_or_create(nombre='Ecuador')
    colombia, _ = Pais.objects.get_or_create(nombre='Colombia')
    
    pichincha, _ = Provincia.objects.get_or_create(nombre='Pichincha', pais=ecuador)
    guayas, _ = Provincia.objects.get_or_create(nombre='Guayas', pais=ecuador)
    antioquia, _ = Provincia.objects.get_or_create(nombre='Antioquia', pais=colombia)

    Ciudad.objects.get_or_create(nombre='Quito', provincia=pichincha)
    Ciudad.objects.get_or_create(nombre='Guayaquil', provincia=guayas)
    Ciudad.objects.get_or_create(nombre='Medellín', provincia=antioquia)

    # --- Creación de Productos ---
    productos = [
        {"nombre": "Taza Inspiradora", "precio": 12.50, "url_imagen": "https://via.placeholder.com/300x300.png?text=Taza", "descripcion": "Taza de cerámica con frases motivacionales para empezar bien el día."},
        {"nombre": "Camiseta Motivacional", "precio": 25.00, "url_imagen": "https://via.placeholder.com/300x300.png?text=Camiseta", "descripcion": "Camiseta cómoda con mensajes que inspiran a lograr tus metas."},
        {"nombre": "Hoodie con Actitud", "precio": 45.00, "url_imagen": "https://via.placeholder.com/300x300.png?text=Hoodie", "descripcion": "Hoodie abrigado y moderno para motivarte en cualquier momento."},
        {"nombre": "Gorra de Metas", "precio": 18.00, "url_imagen": "https://via.placeholder.com/300x300.png?text=Gorra", "descripcion": "Gorra casual para recordarte que siempre puedes más."},
    ]

    for prod_data in productos:
        Producto.objects.get_or_create(nombre=prod_data['nombre'], defaults=prod_data)

def reverse_seed_data(apps, schema_editor):
    # Esta función se podría usar para borrar los datos si deshacemos la migración
    # Por simplicidad, la dejaremos vacía.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]