# Archivo de migración
# Permite agregar el campo descripción a los productos en la base de datos.
# Generated by Django 5.2.3 on 2025-07-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_add_missing_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
