# Archivo de migración
# Aplica cambios en la base de datos (en este caso, agrega el modelo Cupon).
# Generated by Django 5.2.3 on 2025-07-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_fix_province_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento, ej: 10 para 10%', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
