# Generated by Django 5.2.3 on 2025-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_pedido_cupon_aplicado_pedido_descuento_aplicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='frasemotivacional',
            name='destacada',
            field=models.BooleanField(default=False, help_text='Marcar si la frase debe mostrarse en la web (máximo 3)'),
        ),
    ]
